<LessonMenu>
    GridLayout:
        rows:2

        #M3TopAppBar:

        M3RecycleView:

            M3LabelsColumn:

                GoToLessonCard:
                    text: "Глава 1. Правила черчения"
                    secondary_text: "Шрифт, размер, карандаши, ГОСТ"
                    go_to: "first_steps"
                    #source_to_img: app.path_to("view", "images", "template", ext=".png")